package FileOperations;

import java.io.File;

public class DeleteFile {

	public static void main(String[] args) {
try {
	File file = new File("AutoGeneratedFiles/MultipleFiles10.txt");
	file.delete();
	
}catch(Exception e) {
	System.out.println("Some error"+ " "+ e );
}
		
		
	}

}
