package FileOperations;

import java.io.FileWriter;

public class WriteMultipleFilesInFolder {

	public static void main(String[] args) {
		try {
			for(int i=1;i<=10;i++) {
				String FileName = "AutoGeneratedFiles/MultipleFiles"+i+".txt";
				FileWriter writer = new FileWriter(FileName);
				writer.write("This is a dummy file with path and File Name of" +FileName);
				writer.close();
				System.out.println(FileName+" "+"created");
				
			}
		}catch(Exception e) {
			System.out.println("Some error"+" "+ e);
		}

	}

}
